### ISSUE TITLE
Deletion

### ISSUE THREAD

**Issue by upintheairsheep** [afrojer/env-setup#1]
Why did you delete your Instagram and Facebook account? I'm confused.

**Comment by afrojer** [comment]
Please use github issues to discuss feature requests or bug fixes in the relevant repo.

**Comment by upintheairsheep** [comment]
> Please use github issues to discuss feature requests or bug fixes in the relevant repo.

Do you still have any code of Cycada or have the nexus 7 with Cycada? Just curious I’m not forcing you to release it. Already know that if I want the source I contact mr Neih. Sorry for spamming you on unreleased topics. The email system on your site was broken due to a captia bug. So I had to use GitHub. Thank you.
